// app/data.js
export const playerData = [
	{
		rank: 1,
		gamerank: 71,
		firstName: "Trent",
		lastName: "Williams",
		position: "T",
		height: "6-5",
		weight: 320,
		age: 36,
		experience: 15,
		college: "Oklahoma",
	},
	{
		rank: 2,
		gamerank: 72,
		firstName: "Aaron",
		lastName: "Rodgers",
		position: "QB",
		height: "6-2",
		weight: 225,
		age: 39,
		experience: 18,
		college: "California",
	},
	{
		rank: 3,
		gamerank: 73,
		firstName: "Tom",
		lastName: "Brady",
		position: "QB",
		height: "6-4",
		weight: 225,
		age: 46,
		experience: 23,
		college: "Michigan",
	},
	{
		rank: 4,
		gamerank: 74,
		firstName: "Patrick",
		lastName: "Mahomes",
		position: "QB",
		height: "6-3",
		weight: 230,
		age: 28,
		experience: 6,
		college: "Texas Tech",
	},
	{
		rank: 5,
		gamerank: 75,
		firstName: "Davante",
		lastName: "Adams",
		position: "WR",
		height: "6-1",
		weight: 215,
		age: 31,
		experience: 10,
		college: "Fresno State",
	},
	{
		rank: 6,
		gamerank: 76,
		firstName: "Derrick",
		lastName: "Henry",
		position: "RB",
		height: "6-3",
		weight: 247,
		age: 30,
		experience: 8,
		college: "Alabama",
	},
	{
		rank: 7,
		gamerank: 77,
		firstName: "Cooper",
		lastName: "Kupp",
		position: "WR",
		height: "6-2",
		weight: 208,
		age: 30,
		experience: 7,
		college: "Eastern Washington",
	},
	{
		rank: 8,
		gamerank: 78,
		firstName: "Jalen",
		lastName: "Ramsey",
		position: "CB",
		height: "6-1",
		weight: 208,
		age: 29,
		experience: 8,
		college: "Florida State",
	},
	{
		rank: 9,
		gamerank: 79,
		firstName: "Travis",
		lastName: "Kelce",
		position: "TE",
		height: "6-5",
		weight: 260,
		age: 34,
		experience: 11,
		college: "Cincinnati",
	},
	{
		rank: 10,
		gamerank: 80,
		firstName: "Nick",
		lastName: "Bosa",
		position: "DE",
		height: "6-4",
		weight: 266,
		age: 26,
		experience: 5,
		college: "Ohio State",
	},
	{
		rank: 11,
		gamerank: 81,
		firstName: "Josh",
		lastName: "Allen",
		position: "QB",
		height: "6-5",
		weight: 237,
		age: 28,
		experience: 6,
		college: "Wyoming",
	},
	{
		rank: 12,
		gamerank: 82,
		firstName: "Christian",
		lastName: "McCaffrey",
		position: "RB",
		height: "5-11",
		weight: 205,
		age: 28,
		experience: 7,
		college: "Stanford",
	},
	{
		rank: 13,
		gamerank: 83,
		firstName: "George",
		lastName: "Kittle",
		position: "TE",
		height: "6-4",
		weight: 250,
		age: 30,
		experience: 7,
		college: "Iowa",
	},
	{
		rank: 14,
		gamerank: 84,
		firstName: "Aaron",
		lastName: "Donald",
		position: "DT",
		height: "6-1",
		weight: 280,
		age: 33,
		experience: 10,
		college: "Pittsburgh",
	},
	{
		rank: 15,
		gamerank: 85,
		firstName: "Myles",
		lastName: "Garrett",
		position: "DE",
		height: "6-4",
		weight: 272,
		age: 28,
		experience: 7,
		college: "Texas A&M",
	},
	{
		rank: 16,
		gamerank: 86,
		firstName: "Stefon",
		lastName: "Diggs",
		position: "WR",
		height: "6-0",
		weight: 191,
		age: 30,
		experience: 9,
		college: "Maryland",
	},
	{
		rank: 17,
		gamerank: 87,
		firstName: "Micah",
		lastName: "Parsons",
		position: "LB",
		height: "6-3",
		weight: 245,
		age: 25,
		experience: 3,
		college: "Penn State",
	},
	{
		rank: 18,
		gamerank: 88,
		firstName: "Tyreek",
		lastName: "Hill",
		position: "WR",
		height: "5-10",
		weight: 185,
		age: 30,
		experience: 8,
		college: "West Alabama",
	},
	{
		rank: 19,
		gamerank: 89,
		firstName: "Justin",
		lastName: "Jefferson",
		position: "WR",
		height: "6-1",
		weight: 202,
		age: 25,
		experience: 4,
		college: "LSU",
	},
	{
		rank: 20,
		gamerank: 90,
		firstName: "T.J.",
		lastName: "Watt",
		position: "OLB",
		height: "6-4",
		weight: 252,
		age: 30,
		experience: 7,
		college: "Wisconsin",
	},
];
